'use client';

import { ImportsOverTimeChart, LeadsByStatusChart, AIUsageChart } from '@/components/Charts';
import { motion } from 'framer-motion';
import { Sparkles, Calendar } from 'lucide-react';

export default function AnalyticsPage() {
  // Mock data for high-fidelity dashboards
  const importsData = [
    { date: 'Mon', imports: 12 },
    { date: 'Tue', imports: 19 },
    { date: 'Wed', imports: 32 },
    { date: 'Thu', imports: 26 },
    { date: 'Fri', imports: 45 },
    { date: 'Sat', imports: 22 },
    { date: 'Sun', imports: 55 },
  ];

  const leadsByStatusData = [
    { name: 'New', value: 450 },
    { name: 'Contacted', value: 310 },
    { name: 'Qualified', value: 180 },
    { name: 'Lost', value: 60 },
  ];

  const aiUsageData = [
    { provider: 'OpenAI (GPT-4o-mini)', calls: 145 },
    { provider: 'Anthropic (Claude 3.5)', calls: 35 },
    { provider: 'Google (Gemini 1.5)', fill: 20, calls: 82 },
  ];

  return (
    <div className="space-y-8">
      {/* Header */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h2 className="text-2xl font-black tracking-tight text-text-primary">Operational Analytics</h2>
          <p className="text-sm text-text-secondary mt-1">
            Visual metrics mapping platform ingestion growth, status allocations, and LLM mapping distributions.
          </p>
        </div>
        <div className="flex items-center gap-2 bg-bg-secondary border border-border-primary rounded-xl px-4 py-2 text-xs font-semibold text-text-secondary shadow-sm">
          <Calendar className="w-4 h-4" />
          <span>Last 7 Days</span>
        </div>
      </div>

      {/* Grid Charts */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        {/* Weekly Ingestion Traffic */}
        <div className="card p-6">
          <h3 className="text-base font-bold text-text-primary mb-2">Ingestion Traffic</h3>
          <p className="text-xs text-text-secondary mb-6 font-semibold">Total spreadsheet uploads processed per day</p>
          <ImportsOverTimeChart data={importsData} />
        </div>

        {/* AI LLM Provider Usage */}
        <div className="card p-6">
          <h3 className="text-base font-bold text-text-primary mb-2">AI Mapping Engine Calls</h3>
          <p className="text-xs text-text-secondary mb-6 font-semibold">Total batches routed per model provider</p>
          <AIUsageChart data={aiUsageData} />
        </div>

        {/* Lead Conversion Status */}
        <div className="card p-6">
          <h3 className="text-base font-bold text-text-primary mb-2">Lead Conversion Distribution</h3>
          <p className="text-xs text-text-secondary mb-6 font-semibold">Total saved CRM leads grouped by status category</p>
          <LeadsByStatusChart data={leadsByStatusData} />
        </div>

        {/* Cost & Speed Optimization */}
        <div className="card p-6 flex flex-col justify-between">
          <div>
            <h3 className="text-base font-bold text-text-primary mb-2">Performance Optimization Insights</h3>
            <p className="text-xs text-text-secondary mb-6 font-semibold">Platform recommendations generated by analysis metrics</p>
          </div>
          <div className="space-y-4">
            <div className="p-4 bg-accent-bg border border-accent/15 rounded-2xl flex gap-3">
              <Sparkles className="w-5 h-5 text-indigo-500 mt-0.5 flex-shrink-0" />
              <div>
                <p className="text-xs font-bold text-text-primary">LLM Routing Optimizing Recommendation</p>
                <p className="text-[11px] text-text-secondary mt-1 font-semibold leading-normal">
                  Google Gemini 1.5 Flash has demonstrated 45% faster latency times (avg 12s/batch) with 80% lower cost rates. Consider upgrading the default routing profile.
                </p>
              </div>
            </div>
            <div className="p-4 bg-emerald-50 dark:bg-emerald-950/20 border border-emerald-500/10 rounded-2xl flex gap-3">
              <Sparkles className="w-5 h-5 text-emerald-500 mt-0.5 flex-shrink-0" />
              <div>
                <p className="text-xs font-bold text-text-primary">Ingestion Accuracy Spike</p>
                <p className="text-[11px] text-text-secondary mt-1 font-semibold leading-normal">
                  Average spreadsheet row extraction accuracy has stabilized at 94.5% success rate, due to optimized field parsing logic.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
